import { ApiProperty } from '@nestjs/swagger';

export class Recipe {
  @ApiProperty({
    description: 'Recipe Id, generated by uuid',
    type: 'string',
    example: '2313w49-0db7-4v79-aacc-52624343bf2t',
  })
  id: string;

  @ApiProperty({
    description: 'Id of the User who owns this recipe',
    type: 'string',
    example: '2313w49-0db7-4v79-aacc-52624343bf2t',
  })
  ownerId: string;

  @ApiProperty({
    description: 'Recipe title',
    type: 'string',
    example: 'Sun-Dried Tomato Pasta',
  })
  title: string;

  @ApiProperty({
    description: 'List of ingredients, one free-text line each',
    type: 'string',
    isArray: true,
    example: ['200g penne', '2 cloves garlic', 'Fresh basil'],
  })
  ingredients: string[];

  @ApiProperty({
    description: 'Preparation instructions',
    type: 'string',
    example: 'Boil the penne until al dente...',
  })
  instructions: string;

  @ApiProperty({
    description: 'Whether the recipe is marked as favorite',
    type: 'boolean',
    example: false,
  })
  isFavorite: boolean;

  @ApiProperty({
    description: 'Created At',
    type: 'string',
    example: '2026-01-01T00:00:00.000Z',
  })
  createdAt: Date;

  @ApiProperty({
    description: 'Updated At',
    type: 'string',
    example: '2026-01-01T00:00:00.000Z',
  })
  updatedAt: Date;
}
